@startuml C1_1
left to right direction

!include <C4/C4_Context>

title C1, вар.1: Мониторинг ферм с приоритетом локальных вычислений

' Ферма
Enterprise_Boundary(система_фермы, "Ферма") {
 System(farm, \
        "Система мониторинга фермы\n[Edge: IoT-шлюз+AI+HMI]",\
        "Приём данных с устройств, Обработка сырых данных в аналитики,\
          Распознавание состояний животных и инцидентов (инференс модели AI),\
          Отображение и регистрация показателей/событий/инцидентов, Оповещения персонала,\
          Пересчёт поголовья, Трекинг особей (перспектива), Управление кормлением,\
          Передача данных в центр: обработанных аналитик и выборочных сырых, Получение и выполнение команд/настроек из центра",\
          " partly reused")

 Person(employee, "Сотрудник (оператор, животновод, техник)", "Работает на ферме")

 System_Ext(extr_comm, "Система экстренных оповещений",\
                       "Push SMS Радио Телефон Сигнализация")
 System_Ext(vcam, "Видеомониторинг животных\n[IoT]", "Видеонаблюдение")
 System_Ext(rfid, "RFID-мониторинг животных\n[IoT]",\
                  "Поголовный трекинг чипированных особей", "Возможная перспектива")
 System_Ext(sensors, "Мониторинг параметров среды\n[IoT]",\
                     "Съём показаний датчиков (климат, вода, воздух, фильтры, кормохранилища и др.)")
 System_Ext(feeding, "Кормушки и поилки\n[PLC]", "Управление кормушками/поилками")

 Rel(extr_comm, employee , "Экстренные оповещения (инциденты животных, сбои техники)")
 Rel(vcam, farm, "Предоставляет данные видеомониторинга животных")
 Rel(sensors, farm, "Предоставляет данные мониторинга среды")
 Rel(rfid, farm, "Предоставляет данные RFID-мониторинга животных")
 Rel(farm,feeding,"Управляет кормлением")
 Rel(employee, farm, "Авторизуется, работает на ферме с использованием системы")
 Rel(farm,extr_comm,"Оповещает сотрудников")
}


' Центральная платформа / головной офис
Enterprise_Boundary(система, "Центральная платформа (головной офис)") {
  System(center_farm,\
         "Центральное управление свинофермами\n[MES]",\
         "Получение аналитик и выборочных сырых данных с ферм,\
           Запись полученных данных в хранилища,\
           Снятие/визуализация отчётов, Текущий учёт (планирование/прогноз/учёт поголовья, продукции, кормов),\
           Управление фермами (команды, планы/расписания операций, настройки, обновления ПО), API(web/mobile)")

  Person(mainuser, "Управляющий фермой (зоотехник, менеджер)", "Управляет фермой")
  Person(admin, "Сисадмин\n<reused>", "Обслуживает системы, Настраивает доступ пользователей")

  System_Ext(erp,\
             "1С:Агро\n[ERP]",\
             "Склад, Учёт(наличия и движения кормов, поголовья, продукции), Снабжение, Планирование, Нормы",\
             "<existing>")
  System_Ext(bi, "Power BI\n[DWH+DataLake+BI]", "Хранилища данных, Отчеты и визуализация","<existing>")

  Rel(center_farm,erp, "Получает/актуализирует данные учёта производственных процессов на фермах")
  Rel(center_farm,bi, "Отправляет значения аналитик мониторинга, получает отчёты")
  Rel(mainuser,center_farm,"Управляет фермами")
  Rel(farm,center_farm,"Синхронизация: Приём команд/параметров из центра, Передача в центр результатов команд и обработанных аналитик")
  Rel(admin,система,"Обеспечивает работу систем и пользователей")
  Rel(admin,система_фермы,"Обеспечивает работу систем и пользователей")
 }


@enduml