@startuml
title Ferma Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

  title Система фермы в общей архитектуре платформы АгроТех

  Person(user, "Пользователь", "Регистрируется, получает доступ")
  Person(operator, "Оператор", "Работает")
  Person(admin, "Administrator", "An administrator managing the system")
  Person(mainuser, "Животновод", "Управляет фермой")
  System(ferma, "Svinoferma", "Система фермы")
  System(agro_tech, "AgroTech", "Центральная платформа АгроТех")
  System_Ext(extr_comm, "ExtraCommunication", "Система экстренных оповещений")
  Rel(user, ferma, "Использует для работы")
  Rel(operator, ferma, "Мониторит, обслуживает")
  Rel(operator, extr_comm, "Экстренные оповещения")
  Rel(admin,ferma,"Manages the system")
  Rel(ferma,extr_comm,"Оповещает оператора")
  Rel(mainuser,agro_tech,"Управляет фермой в составе центральной платформы")
  Rel(ferma,agro_tech,"Взаимодействуют центр(команды)-ферма(результаты, аналитика)")

@enduml