@startuml
title Ferma Context Diagram

top to bottom direction

!include <C4/C4_Context>

 title Система фермы в общей архитектуре платформы АгроТех

Enterprise_Boundary(система_фермы, "Ферма") {
 System_Ext(extr_comm, "Система экстренных оповещений" , "Push SMS Радио Телефон Сирена Ракетница Гонец Голубь")
 System_Ext(vcam, "Видеомониторинг животных", "Видеонаблюдение, Видеорегистрация, AI-Видеоаналитика (распознавание состояний животных и инцидентов, пересчёт поголовья")
 System_Ext(rfid, "RFID-мониторинг животных", "Мониторинг перемещений чипированных особей, пересчёт поголовья", "Возможная перспектива")
 System_Ext(sensors, "Мониторинг среды", "Датчики (климата, воды, воздуха, фильтров, кормохранилищ, etc)")
 System_Ext(feeding, "Кормушки и поилки", "управление кормлением и водопоем")

  Person(employee, "Сотрудник (оператор, животновод, техник)", "Работает на ферме")
  System(ferma, "Система фермы", "Управляет и получает данные от систем мониторинга, Регистрирует события, Вызывает оповещения, Управляет кормлением, Передаёт аналитику в центр, Получает команды и настройки из центра")
  Rel(extr_comm, employee , "Экстренные оповещения (инциденты животных, сбои техники)")
  Rel(vcam, ferma, "Предоставляет данные видеомониторинга животных")
  Rel(rfid, ferma, "Предоставляет данные RFID-мониторинга животных")
  Rel(sensors, ferma, "Предоставляет данные мониторинга среды")
  Rel(ferma,feeding,"Управляет кормушками и поилками")
  Rel(employee, ferma, "Авторизуется, работает на ферме с использованием системы")
  Rel(ferma,extr_comm,"Оповещает сотрудников")
 }


Enterprise_Boundary(система, "Центральная платформа") {
  Person(mainuser, "Управляющий фермой (зоотехник, менеджер)", "Управляет фермой")
  Person(admin, "Сисадмин", "Обновление ПО центра и ферм, Техподдержка систем, Настройка доступа")
  System(center_farm, "Центральное управление свинофермами", "MES, получение аналитик с ферм, текущий учёт (планирование/прогноз/учёт поголовья, продукции, кормов), управление фермами (планы, команды, настройки, ПО), API(web/mobile)")
  System_Ext(erp, "ERP система (1С:Агро)", "Склад, Учёт(наличия и движения кормов, поголовья, продукции), Снабжение, Планирование, Нормы")
  System_Ext(bi, "BI система (Power BI)", "Отчеты и визуализация")
  Rel(center_farm,erp, "Получает/актуализирует данные учёта производственных процессов на фермах")
  Rel(center_farm,bi, "Отправляет значения аналитик мониторинга, получает отчёты")
  Rel(admin,center_farm,"Обеспечивает работу систем и пользователей")
  Rel(admin,ferma,"Обеспечивает работу систем и пользователей")
  Rel(mainuser,center_farm,"Управляет фермой в составе центральной платформы")
  Rel(ferma,center_farm,"Взаимодействуют центр(команды)-ферма(результаты, аналитика)")
 }


@enduml