@startuml
title Ferma Context Diagram

top to bottom direction

!include <C4/C4_Context>

 title Система фермы в общей архитектуре платформы АгроТех

Enterprise_Boundary(система_фермы, "Ферма") {
 System_Ext(extr_comm, "Система экстренных оповещений" , "Push SMS Радио Телефон Сирена Ракетница Гонец Голубь")
 System_Ext(vcam, "Видеомониторинг животных", "Видеонаблюдение, Видеорегистрация")
 System_Ext(rfid, "RFID-мониторинг животных", "Мониторинг местонахождений чипированных особей", "Возможная перспектива")
 System_Ext(sensors, "Мониторинг параметров среды", "Съём показаний датчиков (климата, воды, воздуха, фильтров, кормохранилищ и др.)")
 System_Ext(feeding, "Кормушки и поилки", "Управление кормушками/поилками")

  Person(employee, "Сотрудник (оператор, животновод, техник)", "Работает на ферме")
  System(farm, "Система фермы", "Управление мониторингом и приём данных, Распознавание состояний животных и инцидентов, Отображение и регистрация показателей/событий/инцидентов, Оповещения персоналу, Пересчёт поголовья, Трекинг особей (перспектива), Управление кормлением, Передача аналитик в центр, Получение и выполнение команд/настроек из центра")
  Rel(extr_comm, employee , "Экстренные оповещения (инциденты животных, сбои техники)")
  Rel(vcam, farm, "Предоставляет данные видеомониторинга животных")
  Rel(rfid, farm, "Предоставляет данные RFID-мониторинга животных")
  Rel(sensors, farm, "Предоставляет данные мониторинга среды")
  Rel(farm,feeding,"Управляет кормлением")
  Rel(employee, farm, "Авторизуется, работает на ферме с использованием системы")
  Rel(farm,extr_comm,"Оповещает сотрудников")
 }


Enterprise_Boundary(система, "Центральная платформа") {
  Person(mainuser, "Управляющий фермой (зоотехник, менеджер)", "Управляет фермой")
  Person(admin, "Сисадмин", "Обновление ПО центра и ферм, Техподдержка систем, Настройка доступа")
  System(center_farm, "Центральное управление свинофермами (MES)", "Получение аналитик с ферм, Текущий учёт (планирование/прогноз/учёт поголовья, продукции, кормов), управление фермами (команды, планы/расписания операций, настройки, ПО), API(web/mobile)")
  System_Ext(erp, "ERP система (1С:Агро)", "Склад, Учёт(наличия и движения кормов, поголовья, продукции), Снабжение, Планирование, Нормы")
  System_Ext(bi, "BI система (Power BI)", "Отчеты и визуализация")
  Rel(center_farm,erp, "Получает/актуализирует данные учёта производственных процессов на фермах")
  Rel(center_farm,bi, "Отправляет значения аналитик мониторинга, получает отчёты")
  Rel(admin,center_farm,"Обеспечивает работу систем и пользователей")
  Rel(admin,farm,"Обеспечивает работу систем и пользователей")
  Rel(mainuser,center_farm,"Управляет фермой в составе центральной платформы")
  Rel(farm,center_farm,"Синхронизация ферма-центр: Передача показателей в центр, Приём команд и параметров из центра")
 }


@enduml