@startuml C2_1
 left to right direction
' top to bottom direction
!include <C4/C4_Container>

title C2, вар.1: Мониторинг ферм с приоритетом локальных вычислений

' Person(admin, "Сисадмин\n<reused>", "Обслуживает системы, Настраивает доступ пользователей")

' Ферма
Enterprise_Boundary(система_фермы, "Ферма") {
 Container(iot_edge, \
        "IoT-шлюз+HMI",\
        "Node-RED + пакеты + JS(node.js)",\
        "Приём данных с устройств, Обработка сырых данных в аналитики,\
          Отображение и регистрация показателей/событий/инцидентов, Оповещения персонала,\
          Пересчёт поголовья, Трекинг особей (перспектива), Управление кормлением,\
          Передача данных в центр: обработанных аналитик и выборочных сырых, Получение и выполнение команд/настроек из центра",\
          " partly reused")

        Container(aiInference, "Инференс ИИ-модели мониторинга животных", "Партнёрская ИИ-модель", "Распознавание количества, состояний животных и инцидентов")
        ContainerDb(tsdb, "Буфер для отправки в центр", "Временные ряды считанных показаний/событий, обработанные данные: агрегаты/аналитики/результаты команд", "PostgreSQL+TimescaleDB", " reused")
        ContainerDb(opdb, "Данные локальной БЛ", "PostgreSQL|SQLite|файлы", "Конфиги, параметры, текущие значения состояний БЛ")

        Rel(iot_edge,tsdb,"Сохраняет данные для отправки в центр", "SQL")
        Rel(iot_edge,opdb,"CRUD", "SQL|файловый I/O")
        Rel(aiInference,iot_edge,"Распознанные данные о поголовье и состоянии", "MQTT|Vendor-based")


 Person(employee, "Сотрудник (оператор, животновод, техник)", "Работает на ферме")

 System_Ext(extr_comm, "Система экстренных оповещений",\
                       "Push SMS Радио Телефон Сигнализация")
 System_Ext(vcam, "Видеомониторинг животных\n[IoT]", "Видеонаблюдение")
 System_Ext(rfid, "RFID-мониторинг животных\n[IoT]",\
                  "Поголовный трекинг чипированных особей", "Возможная перспектива")
 System_Ext(sensors, "Мониторинг параметров среды\n[IoT]",\
                     "Съём показаний датчиков (климат, вода, воздух, фильтры, кормохранилища и др.)")
 System_Ext(feeding, "Кормушки и поилки\n[PLC]", "Управление кормушками/поилками")
 Rel(iot_edge,vcam,"Управляет видеокамерами","ONVIF")
 Rel(extr_comm, employee , "Экстренные оповещения (инциденты животных, сбои техники)", "телекоммуникации, аудиовидео-сигналы")
 Rel(vcam, aiInference, "Аудио/Видео-поток", "RTSP")
 Rel(sensors, iot_edge, "Предоставляет данные мониторинга среды", "MQTT")
 Rel(rfid, iot_edge, "Предоставляет данные RFID-мониторинга животных", "MQTT" )
 Rel(iot_edge,feeding,"Управляет кормлением", "Modbus|MQTT")
 Rel(employee, iot_edge, "Авторизуется, работает на ферме с использованием системы", "HMI(Dashboard)")
 Rel(iot_edge,extr_comm,"Оповещает сотрудников", "Протокол системы опопвещения, опциональное квитирование")
}


' Центральная платформа / головной офис
Enterprise_Boundary(система, "Центральная платформа (головной офис)") {
  System(center_farm,\
         "Центральное управление свинофермами\n[MES]",\
         "Получение аналитик и выборочных сырых данных с ферм,\
           Запись полученных данных в хранилища,\
           Снятие/визуализация отчётов, Текущий учёт (планирование/прогноз/учёт поголовья, продукции, кормов),\
           Управление фермами (команды, планы/расписания операций, настройки, обновления ПО), API(web/mobile)")

  Person(mainuser, "Управляющий фермой (зоотехник, менеджер)", "Управляет фермой")
'  Person(admin, "Сисадмин\n<reused>", "Обновление ПО систем, Техподдержка систем, Настройка доступа")

  System_Ext(erp,\
             "1С:Агро\n[ERP]",\
             "Склад, Учёт(наличия и движения кормов, поголовья, продукции), Снабжение, Планирование, Нормы",\
             "<existing>")
  System_Ext(bi, "Power BI\n[DWH+DataLake+BI]", "Хранилища данных, Отчеты и визуализация","<existing>")

  Rel(center_farm,erp, "Получает/актуализирует данные учёта производственных процессов на фермах")
  Rel(center_farm,bi, "Отправляет значения аналитик мониторинга, получает отчёты")
  Rel(mainuser,center_farm,"Управляет фермами")
  Rel(iot_edge,center_farm,"Синхронизация: Приём команд/параметров из центра, Передача в центр результатов команд и обработанных аналитик")
 ' Person(admin, "Сисадмин\n<reused>", "Обслуживает системы, Настраивает доступ пользователей")
 }
'  Person(admin, "Сисадмин\n<reused>", "Обслуживает системы, Настраивает доступ пользователей")
'  Rel(admin,система,"Обеспечивает работу систем и пользователей")
'  Rel(admin,система_фермы,"Обеспечивает работу систем и пользователей")


@enduml