@startuml C2_1
 left to right direction
' top to bottom direction
!include <C4/C4_Container>

title C2, вар.1: Мониторинг ферм с приоритетом локальных вычислений

' Person(admin, "Сисадмин\n<reused>", "Обслуживает системы, Настраивает доступ пользователей")

' Ферма
Enterprise_Boundary(система_фермы, "Ферма") {
 Container(iot_edge, \
        "IoT-шлюз+HMI",\
        "Node-RED + пакеты + JS(node.js)",\
        "Приём данных с устройств, Обработка сырых данных в аналитики,\
          Отображение и регистрация показателей/событий/инцидентов, Оповещения персонала,\
          Пересчёт поголовья, Трекинг особей (перспектива), Управление кормлением,\
          Передача данных в центр: обработанных аналитик и выборочных сырых, Получение и выполнение команд/настроек из центра",\
          " partly reused")

        Container(aiInference, "Инференс ИИ-модели мониторинга животных", "Партнёрская ИИ-модель", "Распознавание количества, состояний животных и инцидентов")

        ContainerDb(mqtt_db, "Автоматический персистентный буфер брокера MQTT", "SQLite", "bridge.db: Исходящие данные в центр\nretained.db:последние актуальные состояния датчиков/устройств\npersistence.db: текущие сессии и очереди локальных клиентов", " auto by NanoMQ")
        ContainerDb(hist_db, "Локальная база истории (временнЫе ряды)", "InfluxDB+mediafiles", "История телеметрии, событий/инцидентов и связанных видеоотрывков", " optional")
        ContainerDb(media_db,"Хранилище видеофрагментов", "mediafiles", "видеофрагменты событий/инцидентов", " optional")
        Container(mqtt, "MQTT-брокер фермы", "NanoMQ", "Шина данных фермы: Первичные данные+команды MQTT-устройств, обработанные данные IoT-шлюза, мост с центром")

        Rel(mqtt,mqtt_db,"Сохраняет данные для надёжности", "SQL")
        Rel(iot_edge,hist_db,"CRUD", "SQL, mediafiles")
        Rel(iot_edge, mqtt,"Обработка потоков данных и команд", "MQTT")
       Rel(iot_edge, media_db,"files i/o", "mediafiles")
        Rel(aiInference,iot_edge,"Распознанные данные о поголовье и событиях, связанные видеоэпизоды", "gRPC|MQTT|mediafiles")


 Person(employee, "Сотрудник (оператор, животновод, техник)", "Работает на ферме")

 System_Ext(extr_comm, "Система экстренных оповещений",\
                       "Push SMS Радио Телефон Сигнализация")
 System_Ext(vcam, "Видеомониторинг животных\n[IoT]", "Видеонаблюдение")
 ' System_Ext(rfid, "RFID-мониторинг животных\n[IoT]",\
                  "Поголовный трекинг чипированных особей", "Возможная перспектива")
 System_Ext(sensors, "Мониторинг среды, устройств, датчиков животных (RFID)\n[IoT]",\
                     "Съём показаний датчиков (климат, вода, воздух, фильтры, кормохранилища, RFID и др.)")
 System_Ext(feeding, "Кормушки и поилки\n[PLC]", "Управление кормушками/поилками")
 Rel(iot_edge,vcam,"Управляет видеокамерами","ONVIF/RTSP")
 Rel(extr_comm, employee , "Экстренные оповещения (инциденты животных, сбои техники)", "телекоммуникации, радио, аудиовидео-сигналы")
 Rel(vcam, aiInference, "Аудио/Видео-поток", "RTSP/RTP")
 Rel(sensors, iot_edge, "Данные мониторинга", "Modbus|OPC UA")
 Rel(sensors, mqtt, "Данные мониторинга", "MQTT")
 'Rel(rfid, iot_edge, "Данные RFID-мониторинга животных", "OPC UA" )'
 Rel(iot_edge,feeding,"Данные/команды кормления", "MQTT|Modbus|OPC UA")
 Rel(employee, iot_edge, "Авторизуется, работает на ферме с использованием системы", "HMI(Dashboard)")
 Rel(iot_edge,extr_comm,"Оповещает сотрудников", "Протокол системы опопвещения, опциональное квитирование")
}


' Центральная платформа / головной офис
Enterprise_Boundary(система, "Центральная платформа (головной офис)") {
  Container(kafka, "Брокер сообщений", "Apache Kafka", "Шина данных", " existing")
  Container(веб_портал, "Веб-портал", "React", "Управление хозяйством", " existing")

  System_Boundary(center_farm,\
         "Центральное управление свинофермами\n[MES]",\
         "Получение аналитик и выборочных сырых данных с ферм,\
           Запись полученных данных в хранилища,\
           Снятие/визуализация отчётов, Текущий учёт (планирование/прогноз/учёт поголовья, продукции, кормов),\
           Управление фермами (команды, планы/расписания операций, настройки, обновления ПО), API(web/mobile)"){
   Container(mes, "ЦУ свиноферм", "React+node.js", "Оперативное управление свинофермами")
   ContainerDb(mes_db, "Данные БЛ", "PostgreSQL|SQLite",\
    "Конфиги, параметры, текущие значения состояний БЛ оперативного управления свинофермами")
   Rel(mes,mes_db, "CRUD", "SQL")
  }

  Person(mainuser, "Управляющий фермой (зоотехник, менеджер)", "Управляет фермой")
'  Person(admin, "Сисадмин\n<reused>", "Обновление ПО систем, Техподдержка систем, Настройка доступа")
    Container(erp_db, "ERP система (1С:Агро)", "1С", "Финансы, склад, кадры")
'  System_Boundary(erp,\
'             "1С:Агро\n[ERP]",\
'             "Склад, Учёт(наличия и движения кормов, поголовья, продукции), Снабжение, Планирование, Нормы",\
'             "<existing>"){

'  }
  System_Boundary(bisys, "Power BI\n[DWH+DataLake+BI]", "Хранилища данных, Отчеты и визуализация","<existing>"){
      Container_Boundary(данные, "Хранилища данных") {
        ContainerDb(data_lake, "Data Lake", "MinIO", "Сырые данные (S3-совместимое)")
        ContainerDb(dwh, "Data Warehouse", "ClickHouse", "Структурированные данные")
    }

    Container(bi, "BI система", "Power BI", "Отчеты и визуализация")
    Container(аналитика, "Аналитический модуль", "Python+Spark", "Анализ эффективности")
  }

 Rel(kafka, data_lake, "Сырые данные", "Kafka Connect+S3")
 Rel(kafka, dwh, "Трансформированные данные", "ETL+Airflow")
  Rel(kafka, mes, "Оперативные данные и аналитики с ферм", "Kafka")
  Rel(mes,erp_db, "Получает/актуализирует данные учёта производственных процессов на фермах")
  Rel(mes,bi, "Получает отчёты")
  Rel(mainuser,mes,"Управляет свинофермами","HTTPS")
  Rel(веб_портал,mes,"Интеграция управления фермами в общий Веб-портал","HTTPS")
  Rel(mqtt,kafka,"Синхронизация: Приём команд/параметров из центра; Передача в центр аналитик, выборочных сырых данных и результатов команд", MQTT<->Kafka Connect)
  'Rel(mainuser, веб_портал, "Авторизуется через общий портал", "HTTPS")
' Аналитика
Rel(data_lake, аналитика, "Доступ к сырым данным", "Spark")
Rel(dwh, аналитика, "Доступ к структурированным данным", "SQL")
Rel(аналитика, bi, "Передает отчеты", "ODBC")
Rel(аналитика, веб_портал, "Формирует рекомендации", "WebSocket")

' ERP интеграция
Rel(веб_портал, erp_db, "Синхронизация данных", "REST API")
Rel(erp_db, dwh, "Бизнес-данные", "ETL")

 }


@enduml